[build]
  base = "web"
  command = "npm run build"
  publish = "web/.next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://api.rougee.app"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The legacy root index.html has been removed; Next.js handles all routing.
